# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-27 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0006_course_mode_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseemail',
            name='targets',
            field=models.ManyToManyField(blank=True, to='bulk_email.Target'),
        ),
        migrations.AlterField(
            model_name='courseemail',
            name='to_option',
            field=models.CharField(default=b'', max_length=64),
        ),
    ]
